apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: pdb-for-depl
  annotations:
    config.kubernetes.io/local-config: "true"
params:
  pdb:
    apiVersion: policy/v1beta1
    kind: PodDisruptionBudget
    metadata:
      name: nginx-pdb
    spec:
      selector:
        matchLabels:
          app: nginx
      minAvailable: 1
source: |
  def is_pdb(r):
    return r["apiVersion"] == "policy/v1beta1" and r["kind"] == "PodDisruptionBudget" and r["metadata"]["name"] == "nginx-pdb"
  def ensure_pdb(resources, pdb):
    for resource in resources:
      if is_pdb(resource):
        return
    resources.append(pdb)
  pdb = ctx.resource_list["functionConfig"]["params"]["pdb"]
  ensure_pdb(ctx.resource_list["items"], pdb)
