name: verify-docs

on:
  pull_request:
    branches:
      - master
      - '*/v[0-9]+.[0-9]+'

jobs:
  verify-ci:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/kpt-functions-catalog/functions/go
      GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3
      uses: actions/setup-python@v2
    - name: Install libs
      run: |
        pip install pyyaml
    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Install mdrip
      run: |
        go install github.com/monopole/mdrip@v1.0.2
    - name: Verify docs
      run: |
        make verify-docs
